name: 'Git helper composite action'

inputs:
  working-directory:
    required: true
  package-name:
    reqired: true
  version:
    description: 'Bump version (major | minor | patch | alpha)'
    required: true
    default: 'patch'

runs:
  using: "composite"
  steps:

  - name: "echo test"
    run: "echo commit"
    shell: bash

  - name: Bump version
    shell: bash
    working-directory: js
    if: inputs.version != 'alpha'
    run: |
      echo "NEW_VERSION=$(npm version ${{ inputs.version }})" >> $GITHUB_ENV

    # - name: Bump alpha version
    #   working-directory: js
    #   #if: inputs.version == 'alpha'
    #   run: |
    #     echo "NEW_VERSION=$(npm version prerelease --preid=alpha)" >> $GITHUB_ENV

    # - name: Commit and push version
    #   working-directory: js
    #   run: |
    #     git pull
    #     git config user.name "github-actions[bot]"
    #     git config user.email "github-actions[bot]@users.noreply.github.com"
    #     git add package.json
    #     git add package-lock.json
    #     git commit -m "[skip ci] Update SDK beta package ${{ inputs.package-name }}@${{ env.NEW_VERSION }}"
    #     git push
    #     git tag ${{ inputs.package-name }}/${{ env.NEW_VERSION }}
    #     git push --tags
