name: 'Echo'

inputs:
  build-example-app:
    required: false
    type: boolean
    default: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Test echo
      run: echo "Hello from composit action"
      shell: bash
    
    - name: Optional step
      if: inputs.build-example-app == 'true'
      run: echo "Optional"
      shell: bash
