name: 'CommitHelper'
description: 'Commit new version'

inputs:
  package-name:
    description: 'Package name (same as working derictory)'
    required: false
    default: 'vault-wasm'
  version:
    description: 'version'
    required: true
  architecture:
    description: 'arch'
    required: true

runs:
  using: "composite"
  steps:

  - name: Fix git safe directory
    run: echo "commit version ${{ github.event.inputs.version }}"
  
  - name: Echo arch
    run: echo "architecture param - ${{ github.event.inputs.architecture }}"