name: Build WASM

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
    
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
        matrix:
          arch: ['wasm1', 'wasm2']

    steps:
    - uses: actions/checkout@v3

    - name: Run composite action
      uses: ./.github/actions/commit
      with:
        version: ${{ inputs.env }}
        architecture: ${{ matrix.arch }}