name: Build Desktop

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
    
  build:
    name: Build desktop
    runs-on: ubuntu-latest
    strategy:
        matrix:
          arch: ['x64', 'x86']

    steps:
    - uses: actions/checkout@v3

    - name: "Run desktop echo"
      run: echo "Hello from desktop workflow"

    - name: Run composite action
      uses: ./.github/actions/echo

    - name: Commit new version
      uses: ./.github/actions/git-helper
      with:
        working-directory: "rn"
        package-name: "vault.rn"
        version: "alpha"
