name: "[Engine] Build"

on:
  pull_request:

jobs:
  check_code_style:
    name: Check Code style in changed files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v41
      with:
        base_sha: "${{ steps.base-sha.outputs.sha }}"
    
    - name: List all changed files
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        for file in "$ALL_CHANGED_FILES"; do
          echo "$file was changed"
        done
    
    - name: Copy all changed files to temp folder
      run: |
          mkdir -p ${{ github.workspace }}/check-files
          cp -r ${{ steps.changed-files.outputs.all_changed_files }} ${{ github.workspace }}/check-files/

    - name: Run clang-format style check.
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '15'
        check-path: ${{ github.workspace }}/check-files
        fallback-style: 'Microsoft'
