name: Deploy

on:
  workflow_call:
    inputs:
      version:
        description: 'Bump version (major | minor | patch)'
        required: true
        default: 'patch'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build
    
    - name: Config git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Set the value
      id: step_one
      run: echo "action_state=yellow" >> $GITHUB_ENV

    - name: Use the value
      id: step_two
      run: echo "${{ env.action_state }}"

    - name: update version
      run: |
        echo ${{ inputs.version }}
        echo "NEW_VERSION=$(npm version ${{ inputs.version }})" >> $GITHUB_ENV
        echo ${{ env.NEW_VERSION }}

    # - name: Commit and push version
    #   run: |
    #     git add package.json
    #     git add package-lock.json
    #     git commit -m "[skip ci] Update package github-actions-test-repo@${{ env.NEW_VERSION }}"
    #     git push
        
    - name: Commit and push new tag
      run: |
        git tag github-actions-test-repo/${{ env.NEW_VERSION }}
        git push --tags

    - name: Publish npm package
      env:
        NPM_CONFIG_USERCONFIG: .npmrc.ci
        NODE_AUTH_TOKEN: ${{ github.token }}
      run: npm publish --no-git-tag-version
