name: Deploy

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: true
      package-name:
        type: string
        required: true
      version:
        description: 'Bump version (major | minor | patch)'
        required: true
        default: 'patch'
        type: string
      create-release-branch:
        description: 'Automaticaly create a release branch (e.g. release/1.2.3)'
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Commit and publish new version
      uses: ./.github/actions/git-helper
      with:
        working-directory: ${{ inputs.working-directory }}
        package-name: ${{ inputs.package-name }}
        version: ${{ inputs.version }}
        create-release-branch: ${{ inputs.create-release-branch }}
