name: Style

on:
    workflow_call:

jobs:
  check-style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: npm ci

    - name: Check style
      run: npm run lint
