name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Bump version (major | minor | patch)'
        required: true
        default: 'patch'
        type: string
      create-release-branch:
        description: 'Automaticaly create a release branch (e.g. release/1.2.3)'
        type: boolean
        required: false
        default: true

jobs:
  # check-style:
  #   uses: ./.github/workflows/lint.yml
  # build:
  #   needs: [check-style]
  #   uses: ./.github/workflows/build.yml
  # test:
  #   needs: [check-style]
  #   uses: ./.github/workflows/test.yml

  deploy-wasm:
    uses: ./.github/workflows/deploy.yml
    with:
      working-directory: wasm
      package-name: wasm
      version: ${{ github.event.inputs.version }}
      create-release-branch: ${{ github.event.inputs.create-release-branch }}
  
  deploy-js:
    needs: [deploy-wasm]
    uses: ./.github/workflows/deploy.yml
    with:
      working-directory: js
      package-name: js
      version: ${{ github.event.inputs.version }}
      create-release-branch: ${{ github.event.inputs.create-release-branch }}

  # create-pull-request:
  #   runs-on: ubuntu-latest
  #   needs: [deploy-wasm]
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Create Pull Request for Release branch
  #     uses: peter-evans/create-pull-request@v5
  #     with:
  #       title: Release
  #       body: |
  #             - Update package.json release changes
              
  #             Auto-generated by [create-pull-request]
  #       branch: release/v1.2.5
  #       base: main
