name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Bump version (major | minor | patch)'
        required: true
        default: 'patch'
        type: string
      create-release-branch:
        description: 'Automaticaly create a release branch (e.g. release/1.2.3)'
        type: boolean
        required: false
        default: true

jobs:
  check-style:
    uses: ./.github/workflows/lint.yml
  build:
    needs: [check-style]
    uses: ./.github/workflows/build.yml
  test:
    needs: [check-style]
    uses: ./.github/workflows/test.yml

  deploy-wasm:
    uses: ./.github/workflows/deploy.yml
    with:
      working-directory: wasm
      package-name: wasm
      version: ${{ github.event.inputs.version }}
      create-release-branch: ${{ github.event.inputs.create-release-branch }}
  
  deploy-js:
    needs: [deploy-wasm]
    uses: ./.github/workflows/deploy.yml
    with:
      working-directory: js
      package-name: js
      version: ${{ github.event.inputs.version }}
      create-release-branch: ${{ github.event.inputs.create-release-branch }}
