name: Upload Artifacts

on:
    workflow_dispatch:

env:
  ARTIFACTS_ROOT_DIR: ${{ github.workspace }}\test-artifacts

jobs:
  upload-artifacts-tests:
    name: upload
    runs-on: windows-2022
    strategy:
      matrix:
        extension:
          - name: txt
          - name: dll
          - name: pdb
            
         
    steps:
    - uses: actions/checkout@v4

    # Upload
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: TestArtifacts
        path: ${{ env.ARTIFACTS_ROOT_DIR }}\test.${{ matrix.extension.name }}
        retention-days: 1
