name: Deploy app
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Bump version (major | minor | patch)'
        required: true
        default: 'patch'

jobs:
  run-test-workflow:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: ['armeabi-v7a', 'arm64-v8a', 'x86']

    steps:
    - uses: actions/checkout@v3

    - name: Run composite action
      uses: ./.github/actions/commit
      with:
        version: ${{ github.event.inputs.version }}
        architecture: ${{ matrix.arch }}